import { Buffer } from 'node:buffer'
import fs from 'node:fs'
import { createRequire } from 'node:module'
import path from 'node:path'
import process from 'node:process'
import { fileURLToPath } from 'node:url'
import { build } from 'rolldown'
import { isRecord } from '../../packages/rari/src/shared/utils/type-guards.ts'

// Unlike tools/bundle-react-esm, solid-js already ships pure ESM (no CJS
// interop, no webpack chunk-loader shims to strip), so this bundler is far
// simpler: it just re-bundles each vendored entry point into a single flat
// file per the vendor/ directory convention `react_vendor.rs`/`solid_vendor.rs`
// expect. Scope: `solid-js`, `solid-js/web`, `solid-js/h`, `seroval` (the wire
// encoding library used for props/hydration/actions - see
// crates/rari/src/rendering/base/js/solid_props_codec.ts) - no `solid-js/store`,
// no router/meta packages.

const require = createRequire(import.meta.url)
const SCRIPT_DIR = path.dirname(fileURLToPath(import.meta.url))
const ROOT = path.resolve(SCRIPT_DIR, '../..')
const OUT_DIR = path.join(ROOT, 'crates/rari/src/runtime/ext/rari/solid/vendor')

const VENDORED_PACKAGES = ['solid-js', 'seroval'] as const

/**
 * Finds a package's package.json by walking up from its resolved entry
 * point, rather than `require.resolve('pkg/package.json')` - some packages
 * (seroval) have a strict `exports` map with no `"./package.json"` entry,
 * which makes that form fail with ERR_PACKAGE_PATH_NOT_EXPORTED.
 */
function resolvePackageJson(pkg: string): string {
  let dir = path.dirname(require.resolve(pkg))
  for (;;) {
    const candidate = path.join(dir, 'package.json')
    if (fs.existsSync(candidate)) return candidate
    const parent = path.dirname(dir)
    if (parent === dir) throw new Error(`Could not find package.json for "${pkg}"`)
    dir = parent
  }
}

function readVendoredPackageVersions(): Record<string, string> {
  const versions: Record<string, string> = {}
  for (const pkg of VENDORED_PACKAGES) {
    const pkgJsonPath = resolvePackageJson(pkg)
    const parsed: unknown = JSON.parse(fs.readFileSync(pkgJsonPath, 'utf-8'))
    if (!isRecord(parsed) || typeof parsed.version !== 'string')
      throw new Error(`Missing version field in ${pkgJsonPath}`)
    versions[pkg] = parsed.version
  }
  return versions
}

const VENDORED_VERSIONS = readVendoredPackageVersions()

interface BundleEntry {
  readonly name: string
  readonly source: string
  /**
   * Whether `source` has a real default export. solid-js/h does (the
   * hyperscript function itself, consumed as `import h from 'solid-js/h'`);
   * solid-js and solid-js/web don't. `solid_vendor.rs`'s reexport shim
   * always does `export { default }` for every vendor module (matching
   * bundle-react-esm's convention, where CJS interop always synthesizes
   * one), so entries without a real default get one synthesized here as
   * their namespace object - never omitted - to keep that shim uniform.
   */
  readonly hasDefaultExport: boolean
  readonly externals?: Readonly<Record<string, string>>
}

const entries: BundleEntry[] = [
  { name: 'solid-js', source: 'solid-js', hasDefaultExport: false },
  {
    name: 'solid-js-web',
    source: 'solid-js/web',
    hasDefaultExport: false,
    // 'seroval' de-dupes against our own vendored copy (solid-js/web's server
    // build imports it directly for its resource-hydration serialization -
    // see crates/rari/src/rendering/base/js/solid_props_codec.ts for why we
    // vendor it too). 'seroval-plugins/web' (DOM-object plugin support) is
    // left un-externalized/inlined - we don't use it directly.
    externals: {
      'solid-js': 'ext:rari/solid/vendor/solid-js.js',
      seroval: 'ext:rari/solid/vendor/seroval.js',
    },
  },
  {
    name: 'solid-js-h',
    source: 'solid-js/h',
    hasDefaultExport: true,
    externals: { 'solid-js': 'ext:rari/solid/vendor/solid-js.js' },
  },
  { name: 'seroval', source: 'seroval', hasDefaultExport: false },
]

function createVendorHeader(entry: BundleEntry): string {
  const sources = VENDORED_PACKAGES.map(pkg => `${pkg}@${VENDORED_VERSIONS[pkg]}`).join(', ')

  return [
    `/* eslint-disable eslint-comments/no-unlimited-disable */`,
    `/* eslint-disable */`,
    `// oxlint-disable`,
    `/**`,
    ` * Auto-generated ESM bundle of Solid ${entry.name} (production).`,
    ` * Source: ${sources}`,
    ` * Generated by: tools/bundle-solid-esm/bundle.ts`,
    ` *`,
    ` * Do not edit manually. Re-generate with:`,
    ` *   just bundle-solid-esm`,
    ` */`,
    '',
  ].join('\n')
}

/**
 * Rewrites the ESM import specifier for each external package to the shared
 * vendor `ext:` path, so every vendored Solid module resolves to one
 * `solid-js` instance (needed for reactivity to work across module
 * boundaries). Source is pure ESM here (unlike bundle-react-esm's CJS
 * entries), so rolldown always emits a plain `from "pkg"` import specifier
 * for an externalized package - no CJS `__require()` interop to unwind.
 */
function rewriteExternalImports(code: string, externals: Readonly<Record<string, string>>): string {
  let result = code
  for (const [pkg, target] of Object.entries(externals)) {
    const escaped = pkg.replace(/[.*+?^${}()|[\]\\]/g, '\\$&')
    result = result.replace(new RegExp(`from(["'])${escaped}\\1`, 'g'), `from"${target}"`)
  }
  return result
}

function assertExternalsRewritten(entryName: string, code: string, externals: Readonly<Record<string, string>>): void {
  for (const pkg of Object.keys(externals)) {
    const escaped = pkg.replace(/[.*+?^${}()|[\]\\]/g, '\\$&')
    if (new RegExp(`from(["'])${escaped}\\1`).test(code)) {
      throw new Error(`Failed to rewrite external import for "${pkg}" in ${entryName}.`)
    }
  }
}

function writeVendorBundle(entry: BundleEntry, body: string): void {
  const outPath = path.join(OUT_DIR, `${entry.name}.js`)
  const header = createVendorHeader(entry)

  fs.writeFileSync(outPath, header + body, 'utf-8')
  const sizeKb = (Buffer.byteLength(body) / 1024).toFixed(1)
  console.log(`  ${entry.name}.js (${sizeKb} KB)`)
}

async function bundleEntry(entry: BundleEntry): Promise<void> {
  const virtualId = `\0virtual:${entry.name}`
  // The namespace-as-default fallback below (`export default __ns`) doesn't
  // survive Rolldown when the source module is fully inlined rather than
  // external - Rolldown drops it (observed empirically; not documented
  // behavior). Copying into a plain object first (`{ ...__ns }`) avoids
  // whatever dedup/aliasing Rolldown does to a bare re-exported namespace
  // identifier.
  const entrySource = entry.hasDefaultExport
    ? `export * from '${entry.source}';\nexport { default } from '${entry.source}';\n`
    : `import * as __ns from '${entry.source}';\nexport * from '${entry.source}';\nconst __default = { ...__ns };\nexport { __default as default };\n`

  const externalPatterns: (string | RegExp)[] = [/^node:/]
  if (entry.externals) {
    for (const pkg of Object.keys(entry.externals)) {
      // Exact match only - unlike bundle-react-esm's CJS entries (resolved via
      // absolute file paths), these entries use bare package specifiers as
      // `source`, and a `^${pkg}/` prefix pattern would incorrectly externalize
      // an entry's own source (e.g. 'solid-js/web' starts with 'solid-js/').
      // The externalized specifier itself is rewritten to the vendor `ext:`
      // path post-build by rewriteExternalImports below.
      externalPatterns.push(new RegExp(`^${pkg}$`))
    }
  }

  const result = await build({
    input: virtualId,
    platform: 'neutral',
    write: false,
    external: externalPatterns,
    output: {
      format: 'esm',
      minify: true,
      exports: 'named',
    },
    resolve: {
      // 'node' (not 'browser'): solid-js and solid-js/web both have a real
      // server/browser export split (server.js has isServer=true, required
      // for renderToString/renderToStream to work at all - the browser
      // build's SSR functions are stubs that warn and return undefined).
      // We SSR inside V8 on the server, so we need the server build here,
      // same as react_vendor.rs vendoring react-server.js alongside react.js.
      conditionNames: ['production', 'node', 'default'],
    },
    plugins: [
      {
        name: 'virtual-entry',
        resolveId(source) {
          return source === virtualId ? source : null
        },
        load(id) {
          if (id === virtualId) return entrySource
          return null
        },
      },
    ],
  })

  let code = result.output[0].code
  if (entry.externals) {
    code = rewriteExternalImports(code, entry.externals)
    assertExternalsRewritten(entry.name, code, entry.externals)
  }

  writeVendorBundle(entry, code)
}

async function main(): Promise<void> {
  console.log('Bundling Solid ESM for rari...')
  console.log(`  Output: ${path.relative(ROOT, OUT_DIR)}/`)
  console.log('')

  fs.mkdirSync(OUT_DIR, { recursive: true })

  for (const entry of entries) await bundleEntry(entry)

  fs.writeFileSync(
    path.join(OUT_DIR, 'versions.json'),
    `${JSON.stringify(VENDORED_VERSIONS, null, 2)}\n`,
    'utf-8',
  )
  console.log('  versions.json')

  console.log('')
  console.log('Done.')
}

main().catch((err: unknown) => {
  console.error('Bundle failed:', err)
  process.exit(1)
})
